// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2zkfJDmyXgvGrJSCL8Npjj1vZ8snz6w',
    appId: '1:608163842222:android:21eaa7f1d5fc85829b053f',
    messagingSenderId: '608163842222',
    projectId: 'budayapedia-156b3',
    databaseURL: 'https://budayapedia-156b3-default-rtdb.firebaseio.com',
    storageBucket: 'budayapedia-156b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVezrHfv-YSV3UN19AIqsRTbnyNA087k',
    appId: '1:608163842222:ios:eec3fecde2d2c90b9b053f',
    messagingSenderId: '608163842222',
    projectId: 'budayapedia-156b3',
    databaseURL: 'https://budayapedia-156b3-default-rtdb.firebaseio.com',
    storageBucket: 'budayapedia-156b3.firebasestorage.app',
    iosBundleId: 'com.example.budayapedia',
  );
}
